spring.application.name=server
spring.profiles.active=dev
# server.port=2603

## Hibernate JPA
# Auto create by Entity, Is check Entity match DB? False show errors
spring.jpa.hibernate.ddl-auto=validate
# Print SQL Query in terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Print SQL Query by PostgeSQL in terminal
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
# Ex: If load 100 User and each user have list Order (Lazy fetch). Hibernate will run 1 query get User + 100 queries get each Order for each User (error N + 1).
# If applicable, Hibernate will aggregate the queries into a single query.
spring.jpa.properties.hibernate.default_batch_fetch_size=100
